singleQuote: true
semi: false
printWidth: 100
tabWidth: 2
useTabs: false
bracketSpacing: true
endOfLine: auto
eslintIntegration: false
jsxBracketSameLine: true
trailingComma: none
tslintIntegration: false
